FROM ruby:3.4.6-slim

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    git \
    libyaml-dev \
    pkg-config \
    vim \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set working directory
WORKDIR /app

# Install bundler
RUN gem install bundler

# Copy environment files
COPY .env* ./

# Expose port
EXPOSE 3000

# Keep container running
CMD ["tail", "-f", "/dev/null"]
