FROM ruby:3.4.6-slim

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    git \
    libyaml-dev \
    pkg-config \
    vim \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set working directory
WORKDIR /app

# Install bundler
RUN gem install bundler

# Copy Gemfile and install dependencies
COPY Gemfile* ./
RUN bundle install

# Copy environment files
COPY .env* ./

# Copy application code
COPY . .

# Expose port
EXPOSE 3000

# Start Rails server (Rails já tem hot reload nativo em development)
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
