services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rails_api
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      API_TOKEN: development_token
    depends_on:
      - mongo
    stdin_open: true
    tty: true

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  bundle:
